apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}-elasticsearch
  labels:
    app: {{ template "elasticsearch.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  client-config.yml: |
  common-config.yml: |
    path:
      logs: /data/elasticsearch/common-logdir
{{- if .Values.config.commonConfig }}
{{ toYaml .Values.config.commonConfig | indent 4 }}
{{- end }}
  data-config.yml: |
    node:
      name:  es-node-data
    path:
      data: ["/data/elasticsearch/data-datadir"]
    http:
      compression: false
{{- if .Values.config.dataConfig }}
{{ toYaml .Values.config.dataConfig | indent 4 }}
{{- end }}
  master-config.yml: |
    node:
      name:  es-node-master
    path:
      data: ["/data/elasticsearch/master-datadir"]
{{- if .Values.config.masterConfig }}
{{ toYaml .Values.config.masterConfig | indent 4 }}
{{- end }}
