images:
  siliconOperator:
    repository: codejamninja/externaldb-operator
    tag: 0.0.1

config:
  clusterProvider: infrastructure
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  siliconOperator:
    baseUrl: ''
    hostname: ''
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
