apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "n8n.fullname" . }}-n8n
  labels:
    app: {{ template "n8n.name" . }}-n8n
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.persistence.backup.enabled }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "n8n.sharedname" . }}-data
    stash.appscode.com/target-paths: /_data
    stash.appscode.com/volume-mounts: 'data:/_data'
  {{- end }}
spec:
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "n8n.name" . }}-n8n
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "n8n.fullname" . }}-n8n
          image: {{ .Values.images.n8n.repository }}:{{ .Values.images.n8n.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 5678
          volumeMounts:
            - name: data
              mountPath: /_data
            - name: data
              mountPath: '/root/.n8n'
              subPath: data
          env:
           - name: WEBHOOK_TUNNEL_URL
             {{- if .Values.config.gatekeeper.enabled }}
             value: {{ template "n8n.gatekeeper-base-url" . }}
             {{- else }}
             value: {{ template "n8n.n8n-base-url" . }}
             {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "n8n.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- if (and .Values.persistence.backup.enabled (not (empty .Values.persistence.backup.restore.n8nSnapshot))) }}
{{- $restore := .Values.persistence.backup.restore }}
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "n8n.fullname" . }}-n8n
  labels:
    app: {{ template "n8n.name" . }}-n8n
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  driver: Restic
  repository:
    name: {{ template "n8n.sharedname" . }}-n8n
  rules:
    - snapshots:
        - {{ $restore.n8nSnapshot }}
  target:
    paths:
      /_data
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ template "n8n.fullname" . }}-n8n
    volumeMounts:
      - name: data
        mountPath: /_data
{{- end }}
