{{- if .Values.config.phpmyadmin.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "mysql.fullname" . }}-phpmyadmin
  labels:
    app: {{ template "mysql.name" . }}-phpmyadmin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "mysql.name" . }}-phpmyadmin
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "mysql.fullname" . }}-phpmyadmin
          image: {{ .Values.images.phpmyadmin.repository }}:{{ .Values.images.phpmyadmin.tag }}
          imagePullPolicy: {{ .Values.images.phpmyadmin.pullPolicy }}
          ports:
            - name: container
              containerPort: 80
          env:
            - name: PMA_HOST
              value: {{ template "mysql.fullname" . }}-mysql
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}
