{{- if .Values.ingress.sourcegraph.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "sourcegraph.fullname" . }}-sourcegraph
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.sourcegraph.tls }}
    {{- if (empty .Values.ingress.sourcegraph.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.sourcegraph.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "sourcegraph.name" . }}-sourcegraph
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.sourcegraph.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.sourcegraph.path }}
            backend:
              serviceName: {{ template "sourcegraph.fullname" . }}-sourcegraph
              servicePort: http
          - path: {{ .Values.ingress.sourcegraph.path }}/admin
            backend:
              serviceName: {{ template "sourcegraph.fullname" . }}-sourcegraph
              servicePort: admin
  {{- if .Values.ingress.sourcegraph.tls }}
  tls:
    - secretName: {{ template "sourcegraph.sourcegraph-certificate" . }}
      hosts:
        - {{ .Values.ingress.sourcegraph.hostname }}
  {{- end }}
{{- end }}
