{{- if .Values.config.postgres.internal }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarqube.fullname" . }}-postgres
  labels:
    app: {{ template "sonarqube.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: container
  selector:
    app: {{ template "sonarqube.name" . }}-postgres
    release: {{ .Release.Name }}
{{- end }}
