apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: {{ template "mongodb.fullname" . }}-mongodb
  labels:
    app: {{ template "mongodb.name" . }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Values.config.version | quote }}
  {{- if (not (empty .Values.persistence.backup.restore.snapshot)) }}
  databaseSecret:
    secretName: {{ template "mongodb.sharedname" . }}-mongodb-auth
  {{- end }}
  {{- if .Values.config.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if .Values.config.sharding.enabled }}
  shardTopology:
    configServer:
      replicas: {{ .Values.config.sharding.configServerReplicas }}
      configSource:
        configMap:
          name: {{ template "mongodb.fullname" . }}-mongodb
      {{- if .Values.persistence.enabled }}
      storage:
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ''
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- end }}
    mongos:
      replicas: {{ .Values.config.sharding.mongosReplicas }}
      strategy:
        type: {{ .Values.config.updateStrategy }}
      configSource:
        configMap:
          name: {{ template "mongodb.fullname" . }}-mongodb
    shard:
      replicas: {{ .Values.config.replicas }}
      shards: {{ .Values.config.sharding.shards }}
      configSource:
        configMap:
          name: {{ template "mongodb.fullname" . }}-mongodb
      {{- if .Values.persistence.enabled }}
      storage:
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ''
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- end }}
  {{- else }}
  configSource:
    configMap:
      name: {{ template "mongodb.fullname" . }}-mongodb
  {{- if (gt (.Values.config.replicas | int64) 1) }}
  replicas: {{ .Values.config.replicas }}
  replicaSet:
    name: rs0
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- end }}
  {{- end }}
  {{- if (empty .Values.persistence.backup.restore.snapshot) }}
  init:
    scriptSource:
      configMap:
        name: {{ template "mongodb.fullname" . }}-mongodb-init
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.mongodb.type }}
      {{- if (or (eq .Values.service.mongodb.type "LoadBalancer") (eq .Values.service.mongodb.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.mongodb.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: mongodb
          port: 27017
          targetPort: mongodb
          {{- if (and (eq .Values.service.mongodb.type "NodePort") (not (empty .Values.service.mongodb.nodePorts.mongodb))) }}
          nodePort: {{ .Values.service.mongodb.nodePorts.mongodb }}
          {{- end }}
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: {{ .Values.service.mongodb.type }}
      {{- if (or (eq .Values.service.mongodb.type "LoadBalancer") (eq .Values.service.mongodb.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.mongodb.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: mongodb
          port: 27017
          targetPort: mongodb
          {{- if (and (eq .Values.service.mongodb.type "NodePort") (not (empty .Values.service.mongodb.nodePorts.mongodb))) }}
          nodePort: {{ .Values.service.mongodb.nodePorts.mongodb }}
          {{- end }}
  updateStrategy:
    type: {{ .Values.config.updateStrategy }}
  {{- if .Values.persistence.enabled }}
  terminationPolicy: Pause
  {{- else }}
  terminationPolicy: Delete
  {{- end }}
{{- if .Values.persistence.backup.enabled }}
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ template "mongodb.fullname" . }}-mongodb
  labels:
    app: {{ template "mongodb.name" . }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    stash.appscode.com/backup-blueprint: {{ template "mongodb.fullname" . }}-kubedb
spec:
  clientConfig:
    service:
      name: {{ template "mongodb.fullname" . }}-mongodb
      port: 27017
      scheme: mongodb
  type: kubedb.com/mongodb
{{- if (not (empty .Values.persistence.backup.restore.snapshot)) }}
{{- $restore := .Values.persistence.backup.restore }}
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "mongodb.fullname" . }}-mongodb
  labels:
    app: {{ template "mongodb.name" . }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubedb.com/kind: MongoDB
spec:
  driver: Restic
  task:
    name: mongodb-restore-{{ .Values.config.version }}
  repository:
    name: {{ template "mongodb.fullname" . }}-mongodb
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: {{ template "mongodb.fullname" . }}-mongodb
  rules:
    - snapshots:
      - {{ $restore.snapshot }}
{{- end }}
{{- end }}
