{{- if (and .Values.ingress.phpredisadmin.enabled .Values.config.phpredisadmin.enabled) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "redis.fullname" . }}-gitlab
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.phpredisadmin.tls }}
    {{- if (empty .Values.ingress.phpredisadmin.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.phpredisadmin.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "redis.name" . }}-gitlab
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.phpredisadmin.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.phpredisadmin.path }}
            backend:
              serviceName: {{ template "redis.fullname" . }}-gitlab
              servicePort: http
  {{- if .Values.ingress.phpredisadmin.tls }}
  tls:
    - secretName: {{ template "redis.phpredisadmin_certificate" . }}
      hosts:
        - {{ .Values.ingress.phpredisadmin.hostname }}
  {{- end }}
{{- end }}
