images:
  rocketchat:
    repository: rocketchat/rocket.chat
    tag: 2.0.0
  mongoExpress:
    repository: mongo-express
    tag: 0.49.0

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  rocketchat:
    baseUrl: ''
    hostname: ''
  mail:
    smtp:
      host: ''
      port: 25
      username: ''
      password: ''
    from: ''
  jitsi:
    enabled: false
    domain: meet.jit.si
    urlRoomPrefix: RocketChat
    openNewWindow: false
    enableChannels: false
    chromeExtension: ''
  webrtc:
    enableChannel: false
    enablePrivate: false
    enableDirect: false
  mongodb:
    customConfig: ''
    database: rocketchat
    host: ''
    internal: true
    password: ''
    port: 27017
    prometheus: false
    replicas: 1
    url: ''
    username: ''
    version: 4.1.13
    sharding:
      configServerReplicas: 3
      enabled: false
      mongosReplicas: 2
      shards: 3
  mongoExpress:
    enabled: false
    password: pass
    username: admin

service:
  rocketchat:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''
  mongoExpress:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''
  mongodb:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      mongodb: ''

ingress:
  rocketchat:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging
  mongoExpress:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging


persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    googleProjectId: ''
    googleServiceKey: ''
    keepLast: 5
    prefix: ''
    resticPassword: pass
    schedule: '0 0 * * *'
    type: s3
    restore:
      rocketchatsnapshot: ''
      mongodbsnapshot: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
