apiVersion: v1
appVersion: 7.3.2
description: stash-elasticsearch - Elasticsearch database backup and restore plugin
  for Stash by AppsCode
home: https://github.com/stashed/elasticsearch
icon: https://cdn.appscode.com/images/icon/stash.png
maintainers:
- email: support@appscode.com
  name: appscode
name: stash-elasticsearch
sources:
- https://github.com/stashed/elasticsearch
version: 7.3.2
