{{- if (and .Values.config.gatekeeper.enabled .Values.ingress.gatekeeper.enabled) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "n8n.fullname" . }}-gatekeeper
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.gatekeeper.tls }}
    {{- if (empty .Values.ingress.gatekeeper.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.gatekeeper.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "n8n.name" . }}-gatekeeper
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.gatekeeper.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.gatekeeper.path }}/rest
            backend:
              serviceName: {{ template "n8n.fullname" . }}-n8n
              servicePort: http
          - path: {{ .Values.ingress.gatekeeper.path }}
            backend:
              serviceName: {{ template "n8n.fullname" . }}-gatekeeper
              servicePort: http
  {{- if .Values.ingress.gatekeeper.tls }}
  tls:
    - secretName: {{ template "n8n.gatekeeper-certificate" . }}
      hosts:
        - {{ .Values.ingress.gatekeeper.hostname }}
  {{- end }}
{{- end }}
