apiVersion: v1
appVersion: 8.0.14
description: stash-mysql - MySQL database backup and restore plugin for Stash by AppsCode
home: https://github.com/stashed/mysql
icon: https://cdn.appscode.com/images/icon/stash.png
maintainers:
- email: support@appscode.com
  name: appscode
name: stash-mysql
sources:
- https://github.com/stashed/mysql
version: 8.0.14
