images:
  bitwardenrs:
    repository: bitwardenrs/server
    tag: latest

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  bitwardenrs:
    baseUrl: ''
    hostname: ''

service:
  bitwardenrs:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''

ingress:
  bitwardenrs:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    googleProjectId: ''
    googleServiceKey: ''
    keepLast: 5
    prefix: ''
    resticPassword: pass
    schedule: '0 0 * * *'
    type: s3
    restore:
      bitwardenRsSnapshot: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
