{{- if (and .Values.ingress.phpmyadmin.enabled .Values.config.phpmyadmin) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "mysql.fullname" . }}-phpmyadmin
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.phpmyadmin.tls }}
    {{- if (empty .Values.ingress.phpmyadmin.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.phpmyadmin.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "mysql.name" . }}-phpmyadmin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.phpmyadmin.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.phpmyadmin.path }}
            backend:
              serviceName: {{ template "mysql.fullname" . }}-phpmyadmin
              servicePort: http
  {{- if .Values.ingress.phpmyadmin.tls }}
  tls:
    - secretName: {{ template "mysql.phpmyadmin-certificate" . }}
      hosts:
        - {{ .Values.ingress.phpmyadmin.hostname }}
  {{- end }}
{{- end }}
