name: wiki
home: https://github.com/Requarks/wiki.git
icon: https://wiki.js.org/assets/svg/logo.svg
version: 0.0.1
appVersion: latest
description: 'modern and powerful wiki app'
keywords:
  - wiki
sources:
  - https://github.com/Requarks/wiki.git
maintainers:
  - name: 'Jam Risser'
    email: jam@codejam.ninja
