apiVersion: v1
kind: Secret
metadata:
  name: {{ template "directus.fullname" . }}-mysql-auth
  labels:
    app: {{ template "directus.name" . }}-mysql-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.config.mysql.password | b64enc }}
  username: {{ "root" | b64enc }}
