{{- if .Values.config.gatekeeper.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "n8n.fullname" . }}-gatekeeper
  labels:
    app: {{ template "n8n.name" . }}-gatekeeper
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
    client-id: {{ .Values.config.gatekeeper.keycloak.clientId | quote }}
    client-secret: {{ .Values.config.gatekeeper.keycloak.clientSecret | quote }}
    cors-credentials: false
    cors-exposed-headers: []
    cors-headers: []
    cors-max-age: 1h
    cors-methods: []
    cors-origins: []
    discovery-url: {{ .Values.config.gatekeeper.keycloak.baseUrl }}/auth/realms/master
    enable-default-deny: true
    enable-encrypted-token: false
    enable-json-logging: true
    enable-logging: true
    enable-refresh-tokens: false
    enable-security-filter: true
    enable-session-cookies: true
    encryption-key: 1234567890123456
    headers: {}
    listen: 0.0.0.0:3000
    no-redirects: false
    preserve-host: true
    redirection-url: {{ template "n8n.gatekeeper-base-url" . }}
    resources:
      - uri: /*
      - uri: /rest/*
        white-list: true
    scopes: []
    secure-cookie: false
    skip-upstream-tls-verify: true
    tls-ca-certificate:
    tls-cert:
    tls-private-key:
    upstream-keepalives: true
    upstream-url: http://{{ template "n8n.fullname" . }}-n8n
{{- end }}
