{{- if .Values.ingress.directus.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "directus.fullname" . }}-directus
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.directus.tls }}
    {{- if (empty .Values.ingress.directus.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.directus.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "directus.name" . }}-directus
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.directus.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.directus.path }}
            backend:
              serviceName: {{ template "directus.fullname" . }}-directus
              servicePort: http
  {{- if .Values.ingress.directus.tls }}
  tls:
    - secretName: {{ template "directus.directus-certificate" . }}
      hosts:
        - {{ .Values.ingress.directus.hostname }}
  {{- end }}
{{- end }}
