apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    app: {{ template "nextcloud.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nextcloud_username: {{ .Values.config.nextcloud.username | quote }}
  {{- $postgres := .Values.config.postgres }}
  {{- if $postgres.internal }}
  postgres_host: {{ template "nextcloud.fullname" . }}-postgres
  {{- else }}
  postgres_host: {{ $postgres.host | quote }}
  {{- end }}
  postgres_database: {{ $postgres.database | quote }}
  postgres_port: {{ $postgres.port | quote }}
  postgres_username: {{ $postgres.username | quote }}
  {{- if .Values.config.pgadmin.enabled }}
  pgadmin_email: {{ .Values.config.pgadmin.email | quote }}
  {{- end }}
  objectstore_bucket: {{ .Values.config.nextcloud.objectstore.bucket | quote }}
  objectstore_key: {{ .Values.config.nextcloud.objectstore.key | quote }}
  objectstore_region: {{ .Values.config.nextcloud.objectstore.region | quote }}
