name: sonarqube
home: https://www.sonarqube.org
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
version: 0.1.0
appVersion: latest
description: 'the leading product for continuous code quality'
keywords:
  - sonarqube
  - qc
  - quality
  - control
  - continuous
  - code
sources:
  - https://github.com/SonarSource/sonarqube.git
maintainers:
  - name: 'Jam Risser'
    email: jam@codejam.ninja
