{{- if (not (and (eq .Values.config.terminationPolicy "Pause") .Values.config.pause)) }}
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: {{ template "postgres.fullname" . }}-postgres
  labels:
    app: {{ template "postgres.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Values.config.version | quote }}
  configSource:
    configMap:
      name: {{ template "postgres.fullname" . }}-postgres
  standbyMode: {{ .Values.config.standbyMode | quote }}
  streamingMode: asynchronous
  leaderElection:
    leaseDurationSeconds: 15
    renewDeadlineSeconds: 10
    retryPeriodSeconds: 2
  databaseSecret:
    secretName: {{ template "postgres.fullname" . }}-postgres-auth
  {{- if .Values.config.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if (gt (.Values.config.replicas | int64) 1) }}
  replicas: {{ .Values.config.replicas }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if (empty .Values.persistence.stash.restore.snapshot) }}
  init:
    scriptSource:
      configMap:
        name: {{ template "postgres.fullname" . }}-postgres-init
  {{- end }}
  podTemplate:
    {{- if .Values.persistence.velero.enabled }}
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
    {{- end }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: group
                    operator: In
                    values:
                      - dedicated
{{ toYaml .Values.config.resources | indent 8 }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.postgres.type }}
      {{- if (or (eq .Values.service.postgres.type "LoadBalancer") (eq .Values.service.postgres.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.postgres.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: postgres
          port: 5432
          targetPort: postgres
          {{- if (and (eq .Values.service.postgres.type "NodePort") (not (empty .Values.service.postgres.nodePorts.postgres))) }}
          nodePort: {{ .Values.service.postgres.nodePorts.postgres }}
          {{- end }}
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: {{ .Values.service.postgres.type }}
      {{- if (or (eq .Values.service.postgres.type "LoadBalancer") (eq .Values.service.postgres.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.postgres.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: postgres
          port: 5432
          targetPort: postgres
          {{- if (and (eq .Values.service.postgres.type "NodePort") (not (empty .Values.service.postgres.nodePorts.postgres))) }}
          nodePort: {{ .Values.service.postgres.nodePorts.postgres }}
          {{- end }}
  updateStrategy:
    type: {{ (eq .Values.config.updateStrategy "Recreate") | ternary "RollingUpdate" .Values.config.updateStrategy }}
  terminationPolicy: {{ .Values.config.terminationPolicy }}
{{- if .Values.persistence.stash.enabled }}
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ template "postgres.fullname" . }}-postgres
  labels:
    app: {{ template "postgres.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: kubedb.com/postgres
  version: {{ .Values.config.version | quote }}
  clientConfig:
    service:
      name: {{ template "postgres.fullname" . }}-postgres
      path: /
      port: 5432
      query: sslmode=disable
      scheme: postgresql
  secretTransforms:
    - renameKey:
        from: POSTGRES_USER
        to: username
    - renameKey:
        from: POSTGRES_PASSWORD
        to: password
{{- if (not (empty .Values.persistence.stash.restore.snapshot)) }}
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "postgres.fullname" . }}-postgres
  labels:
    app: {{ template "postgres.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubedb.com/kind: Postgres
spec:
  driver: Restic
  task:
    name: postgres-restore-{{ index .Values.config.versionMap .Values.config.version }}
  repository:
    name: postgres-{{ template "postgres.fullname" . }}-postgres
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: {{ template "postgres.fullname" . }}-postgres
  rules:
    - snapshots:
      - {{ .Values.persistence.stash.restore.snapshot | quote }}
{{- end }}
{{- end }}
{{- end }}
