{{- if (not (and (eq .Values.config.terminationPolicy "Pause") .Values.config.pause)) }}
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: {{ template "elasticsearch.fullname" . }}-elasticsearch
  labels:
    app: {{ template "elasticsearch.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Values.config.version | quote }}
  configSource:
    configMap:
      name: {{ template "elasticsearch.fullname" . }}-elasticsearch
  databaseSecret:
    secretName: {{ template "elasticsearch.sharedname" . }}-elasticsearch-auth
  {{- if .Values.config.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  authPlugin: SearchGuard
  enableSSL: false
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if .Values.config.topology.enabled }}
  topology:
    master:
      {{- if (gt (.Values.config.topology.master.replicas | int64) 1) }}
      replicas: {{ .Values.config.topology.master.replicas }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      storage:
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ''
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- end }}
      prefix: master
      maxUnavailable: 0
      resources:
{{ toYaml .Values.config.topology.master.resources | indent 8 }}
    data:
      {{- if (gt (.Values.config.topology.data.replicas | int64) 1) }}
      replicas: {{ .Values.config.topology.data.replicas }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      storage:
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ''
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- end }}
      prefix: data
      maxUnavailable: 0
      resources:
{{ toYaml .Values.config.topology.data.resources | indent 8 }}
    client:
      {{- if (gt (.Values.config.topology.client.replicas | int64) 1) }}
      replicas: {{ .Values.config.topology.client.replicas }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      storage:
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ''
        {{- else }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- end }}
      prefix: client
      maxUnavailable: 0
      resources:
{{ toYaml .Values.config.topology.client.resources | indent 8 }}
  {{- else }}
  {{- if (gt (.Values.config.replicas | int64) 1) }}
  replicas: {{ .Values.config.replicas }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- end }}
  maxUnavailable: 0
  {{- end }}
  {{- if (or .Values.persistence.velero.enabled (not .Values.config.topology.enabled)) }}
  podTemplate:
    {{- if .Values.persistence.velero.enabled }}
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
    {{- end }}
    {{- if (not .Values.config.topology.enabled) }}
    spec:
      resources:
{{ toYaml .Values.config.resources | indent 8 }}
    {{- end }}
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.elasticsearch.type }}
      {{- if (or (eq .Values.service.elasticsearch.type "LoadBalancer") (eq .Values.service.elasticsearch.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.elasticsearch.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: http
          port: 9200
          targetPort: http
          {{- if (and (eq .Values.service.elasticsearch.type "NodePort") (not (empty .Values.service.elasticsearch.nodePorts.elasticsearch))) }}
          nodePort: {{ .Values.service.elasticsearch.nodePorts.elasticsearch }}
          {{- end }}
  updateStrategy:
    type: {{ (eq .Values.config.updateStrategy "Recreate") | ternary "RollingUpdate" .Values.config.updateStrategy }}
  terminationPolicy: {{ .Values.config.terminationPolicy }}
{{- if .Values.persistence.stash.enabled }}
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ template "elasticsearch.fullname" . }}-elasticsearch
  labels:
    app: {{ template "elasticsearch.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: kubedb.com/elasticsearch
  version: {{ .Values.config.version | quote }}
  clientConfig:
    service:
      name: {{ template "elasticsearch.fullname" . }}-elasticsearch
      port: 9200
      scheme: http
  secretTransforms:
    - renameKey:
        from: ADMIN_USERNAME
        to: username
    - renameKey:
        from: ADMIN_PASSWORD
        to: password
{{- if (not (empty .Values.persistence.stash.restore.snapshot)) }}
---
apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: {{ template "elasticsearch.fullname" . }}-elasticsearch
  labels:
    app: {{ template "elasticsearch.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kubedb.com/kind: Elasticsearch
spec:
  driver: Restic
  task:
    name: elasticsearch-restore-{{ index .Values.config.versionMap .Values.config.version }}
  repository:
    name: {{ .Values.persistence.stash.repository | quote }}
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: {{ template "elasticsearch.fullname" . }}-elasticsearch
  rules:
    - snapshots:
      - {{ .Values.persistence.stash.restore.snapshot | quote }}
{{- end }}
{{- end }}
{{- end }}
