{{- if .Values.config.mysql.internal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dbtest.fullname" . }}-mysql
  labels:
    app: {{ template "dbtest.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if (eq (substr 0 1 .Values.config.mysql.version) "8") }}
  default-authentication-plugin.cnf: |
    [mysqld]
    default_authentication_plugin = {{ .Values.config.mysql.authenticationPlugin }}
  {{- end }}
  my-config.cnf: {{ .Values.config.mysql.customConfig | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dbtest.fullname" . }}-mysql-init
  labels:
    app: {{ template "dbtest.name" . }}-mysql-init
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.config.mysql.database }};
{{- end }}
