apiVersion: v1
kind: Service
metadata:
  name: {{ template "gluu.fullname" . }}-oxd
  labels:
    app: {{ template "gluu.name" . }}-oxd
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: container
  selector:
    app: {{ template "gluu.name" . }}-oxd
    release: {{ .Release.Name }}
