{{- if .Values.config.mongodb.internal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rocketchat.fullname" . }}-mongodb
  labels:
    app: {{ template "rocketchat.name" . }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  mongodbd.conf: {{ .Values.config.mongodb.customConfig | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rocketchat.fullname" . }}-mongodb-init
  labels:
    app: {{ template "rocketchat.name" . }}-mongodb-init
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  data.js: ''
