{{- if .Values.config.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgres.fullname" . }}-pgadmin
  labels:
    app: {{ template "postgres.name" . }}-pgadmin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "postgres.name" . }}-pgadmin
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "postgres.name" . }}-pgadmin
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "postgres.fullname" . }}-pgadmin
          image: {{ .Values.images.pgadmin.repository }}:{{ .Values.images.pgadmin.tag }}
          imagePullPolicy: {{ .Values.images.pgadmin.pullPolicy }}
          ports:
            - name: container
              containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "postgres.fullname" . }}
                  key: pgadmin_email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgres.fullname" . }}
                  key: pgadmin_password
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}
