{{- if .Values.ingress.flectra.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "flectra.fullname" . }}-flectra
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: {{ template "flectra.flectra-base-url" . }}/web
    {{- if .Values.ingress.flectra.tls }}
    {{- if (empty .Values.ingress.flectra.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.flectra.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "flectra.name" . }}-flectra
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.flectra.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.flectra.path }}
            backend:
              serviceName: {{ template "flectra.fullname" . }}-flectra
              servicePort: http
  {{- if .Values.ingress.flectra.tls }}
  tls:
    - secretName: {{ template "flectra.flectra-certificate" . }}
      hosts:
        - {{ .Values.ingress.flectra.hostname }}
  {{- end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "flectra.fullname" . }}-flectra-web
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.flectra.tls }}
    {{- if (empty .Values.ingress.flectra.certificate) }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.flectra.issuer.name }}
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    {{- end }}
  labels:
    app: {{ template "flectra.name" . }}-flectra-web
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.flectra.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.flectra.path }}.*
            backend:
              serviceName: {{ template "flectra.fullname" . }}-flectra
              servicePort: http
  {{- if .Values.ingress.flectra.tls }}
  tls:
    - secretName: {{ template "flectra.flectra-certificate" . }}
      hosts:
        - {{ .Values.ingress.flectra.hostname }}
  {{- end }}
{{- end }}
