apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wiki.fullname" . }}
  labels:
    app: {{ template "wiki.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  db_pass: {{ .Values.config.dbPass | b64enc }}
  {{- $postgres := .Values.config.postgres }}
  postgres_url: {{ $postgres.url | b64enc }}
  postgres_password: {{ $postgres.password | b64enc }}
  {{- if .Values.config.pgadmin.enabled }}
  pgadmin_password: {{ .Values.config.pgadmin.password | b64enc }}
  {{- end }}
