images:
  n8n:
    repository: codejamninja/n8n
    tag: 0.36.1
  gatekeeper:
    repository: quay.io/keycloak/keycloak-gatekeeper
    tag: 8.0.0

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  baseUrl: ''
  n8n:
    baseUrl: ''
    hostname: ''
  gatekeeper:
    enabled: false
    baseUrl: ''
    hostname: ''
    keycloak:
      baseUrl: ''
      clientId: ''
      clientSecret: ''

service:
  n8n:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''
  gatekeeper:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''

ingress:
  n8n:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging
  gatekeeper:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    googleProjectId: ''
    googleServiceKey: ''
    keepLast: 5
    prefix: ''
    resticPassword: pass
    schedule: '0 0 * * *'
    type: s3
    restore:
      n8nSnapshot: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
