name: taiga
home: https://www.taiga.com
icon: https://fitsmallbusiness.com/wp-content/uploads/2017/09/taiga-1.png
version: 0.1.0
appVersion: 1.15.3
description: |
  free and open source project management tool
keywords:
  - file-server
  - http-cache
  - load-balancer
  - mail-proxy
  - proxy
  - reverse-proxy
  - server
sources:
  - http://hg.taiga.org/taiga
maintainers:
  - name: 'Jam Risser'
    email: jam@codejam.ninja
