apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app: {{ template "rocketchat.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  base_url: {{ template "rocketchat.base-url" . }}
  jitsi_chrome_extension: {{ .Values.config.jitsi.chromeExtension }}
  jitsi_domain: {{ .Values.config.jitsi.domain }}
  jitsi_enable_channels: {{ .Values.config.jitsi.enableChannels | quote }}
  jitsi_enabled: {{ .Values.config.jitsi.enabled | quote }}
  jitsi_open_new_window: {{ .Values.config.jitsi.open_newWindow | quote }}
  jitsi_url_room_prefix: {{ .Values.config.jitsi.url_roomPrefix }}
  mail_from: {{ .Values.config.mail.from }}
  mail_smtp_host: {{ .Values.config.mail.smtp.host }}
  mail_smtp_port: {{ .Values.config.mail.smtp.port | quote }}
  mail_smtp_username: {{ .Values.config.mail.smtp.username }}
  webrtc_enable_channel: {{ .Values.config.webrtc.enableChannel | quote }}
  webrtc_enable_direct: {{ .Values.config.webrtc.enableDirect | quote }}
  webrtc_enable_private: {{ .Values.config.webrtc.enablePrivate | quote }}
  {{- if .Values.config.mongoExpress.enabled }}
  mongo_express_username: {{ .Values.config.mongoExpress.username | quote }}
  {{- end }}
