name: mongo
home: https://www.mongodb.com
icon: https://avatars1.githubusercontent.com/u/45120?s=200&v=4
version: 0.0.1
appVersion: latest
description: 'the database for modern applications'
keywords:
  - mongo
  - database
  - document
  - db
sources:
  - https://github.com/mongodb/mongo
maintainers:
  - name: 'Jam Risser'
    email: jam@codejam.ninja
