apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app: {{ template "rocketchat.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $mail := .Values.config.mail }}
  {{- $mongodb := .Values.config.mongodb }}
  mongodb_url: {{ $mongodb.url | b64enc }}
  mongodb_password: {{ $mongodb.password | b64enc }}
  {{- if .Values.config.mongoExpress.enabled }}
  mongo_express_password: {{ .Values.config.mongoExpress.password | b64enc }}
  {{- end }}
  mail_smtp_password: {{ $mail.smtp.password | b64enc }}
  mail_smtp_url: {{ printf "smtp://%s:%s@%s:%.0f" $mail.smtp.username $mail.smtp.password $mail.smtp.host $mail.smtp.port | b64enc }}
