apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.fullname" . }}-mongodb-auth
  labels:
    app: {{ template "mongodb.name" . }}-mongodb-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.config.password | b64enc }}
  username: {{ "mongodb" | b64enc }}
